name:                gitty
version:             0.1.0.0
github:              "githubuser/gitty"
license:             BSD-3-Clause
author:              "Pedro Veloso"
maintainer:          "contatopedrohalves@gmail.com"
copyright:           "2026 Pedro Veloso"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pedrohaveloso/gitty#readme>

dependencies:
- base >= 4.7 && < 5

- containers >= 0.7
- bytestring >= 0.12.2.0
- directory >= 1.3.8.5
- filepath >= 1.5.4.0
- split >= 0.2

# crypto
- cryptohash-sha1 >= 0.11.101.0
# compression
- zlib >= 0.7.1.1
# posix
- unix >= 2.8
# terminal commands parser
- optparse-applicative >= 0.18.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gitty:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitty

tests:
  gitty-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitty
